# Generated by Django 4.2.1 on 2023-05-12 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='available_accounts',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
