# Generated by Django 4.2.1 on 2023-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_available_accounts_blog_available_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
