# Generated by Django 4.2.1 on 2023-05-12 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='available_blogs',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
