# Generated by Django 4.2.1 on 2023-05-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='available_blogs',
        ),
    ]
