# Generated by Django 4.2.1 on 2023-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_tag_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='blog',
            new_name='post',
        ),
    ]
